<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <RootNamespace>MChub.Bedrock</RootNamespace>
        <PlatformTarget Condition="'$(RuntimeIdentifier)' == 'win-arm64'">arm64</PlatformTarget>
        <PlatformTarget Condition="'$(PlatformTarget)' == ''">x64</PlatformTarget>
        <NativeInjectorResource>$(MSBuildThisFileDirectory)..\MChub.Bedrock.Injector\MChub.Inject.dll</NativeInjectorResource>
        <NativeBootstrapResource>$(MSBuildThisFileDirectory)..\MChub.Bedrock.Bootstrap\MChub.Bootstrap.dll</NativeBootstrapResource>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\MChub.Bedrock.Core\MChub.Bedrock.Core.csproj" />
      <ProjectReference Include="..\MChub.Bedrock.Core.Windows\MChub.Bedrock.Core.Windows.csproj" />
      <ProjectReference Include="..\MChub.Bedrock.Xbox\MChub.Bedrock.Xbox.csproj" />
      <ProjectReference Include="..\MChub.Bedrock.Standard\MChub.Bedrock.Standard.csproj" />
      <ProjectReference Include="..\MChub.Bedrock.PeNet\src\PeNet\MChub.Bedrock.PeNet.csproj" />
      <ProjectReference Include="..\MChub.Localization\MChub.Localization.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="..\MChub.Bedrock.Preload\MChub.Preload.dll"
                        LogicalName="MChub.Preload.dll" />
      <EmbeddedResource Include="$(NativeInjectorResource)"
                        LogicalName="MChub.Inject.dll" />
      <EmbeddedResource Include="$(NativeBootstrapResource)"
                        LogicalName="MChub.Bootstrap.dll" />
    </ItemGroup>

</Project>
